### ISSUE TITLE
Convert to a RESTful API

### ISSUE THREAD

**Issue by LaurentGoderre** [benbalter/Site-Inspector-php#6]
This would be useful to many and would benefit from being a restful for which a single URL or a comma separated list can be sent via POST and the API would return the info in XML and JSON (output specified via the querystring).

You could then modify the display page to call the service and display the information.

This would allow integrating this information in other scripts.

**Comment by benbalter** [comment]
Adding `&format=json` to the end of the url e.g., `?domain=ben.balter.com&format=json` should return the data as a JSON feed.
